docker:
    base_url: unix://var/run/docker.sock

containers:

    influxdb:
        image: tutum/influxdb
        interface: 0.0.0.0
        entrypoint:
        auth:
            user: root
            password: root
        export:
            wait_for_port: db
            ports:
                - port: 8083
                  name: admin
                - port: 8086
                  name: db

    rethinkdb:
        image: dockerfile/rethinkdb:latest
        interface: 0.0.0.0
        auth:
            user:
            password:
        entrypoint:
        export:
            wait_for_port: db
            ports:
                - port: 8080
                  name: admin
                - port: 28015
                  name: db

    elasticsearch:
        image: dockerfile/elasticsearch
        interface: 0.0.0.0
        auth:
            user:
            password:
        entrypoint:
        export:
            wait_for_port: db
            ports:
                - port: 9200
                  name: db
